
# inbox new stuff detection: watchdog (inotify or crawler)
DETECT_METHOD_WATCHDOG=0
DETECT_METHOD_CRAWLING=1

#
TO_BE_IMPLEMENTED='TO_BE_IMPLEMENTED'

# manager
FORMAT_TEXT='FORMAT_TEXT'
FORMAT_JSON='FORMAT_JSON'

# input item: dict
INPUT_ITEM_SRC_PATH='src_path'
INPUT_ITEM_SRC_RELATIVE_PATH='rel_path'
INPUT_ITEM_PRODUCTION_ID='prod_id'
# web request bits
WEB_REQUEST_BITS='WEB_REQUEST_BITS'
#
DONE_FLAG_FILE_ORCHESTRATOR='orchestrator'
DONE_FLAG_FILE_ID='id'
DONE_FLAG_FILE_AT='at'
DONE_FLAG_FILE_TIME='time'
DONE_FLAG_FILE_CTIME='ctime'
DONE_FLAG_FILE_EXIT_CODE='exitCode'
DONE_FLAG_FILE_STATE='state'
DONE_FLAG_FILE_SOURCE='source'
DONE_FLAG_FILE_SOURCE_SIZE='sourceSize'
DONE_FLAG_FILE_SOURCE_MD5='sourceMd5'
DONE_FLAG_FILE_EOSIP='eosip'
DONE_FLAG_FILE_EOSIP_SIZE='eosipSize'
DONE_FLAG_FILE_EOSIP_MD5='eosipMd5'
DONE_FLAG_FILE_PROCESSING_TIME='processingTime'

# proto command handler
TYPE='type'
PAYLOAD='payload'
API_OP='op'
API_DATA='data'

# redis
REDIS_CHANNEL='REDIS_CHANNEL'
REDIS_MESSAGE='REDIS_MESSAGE'
REDIS_COMMAND='REDIS_COMMAND'